import PDFKit from "pdfkit";
import type { ExportContractBody } from "../schemas/contracts.schema";

type ExportInput = ExportContractBody;

interface Summary {
  totalClauses: number;
  riskyClausesCount: number;
  moderateRiskClausesCount: number;
  overallRiskLevel: "High" | "Medium" | "Low";
  overview?: string;
}
interface Missing {
  clauseName: string;
  suggestion: string;
  importance: "Critical" | "Recommended";
}
interface Social {
  flaggedText: string;
  explanation: string;
}
interface XaiExplanationEntry {
  word: string;
  importance: number;
  reason: string;
}
interface Clause {
  clauseNumber: number;
  clauseText: string;
  clauseType: string;
  riskLevel: "Risky" | "Moderate Risk" | "Low Risk";
  riskScore: number;
  legalBasis: string;
  explanation: string;
  suggestion: string;
  xaiExplanation: XaiExplanationEntry[];
}
interface ChangeEntry {
  clauseNumber: number | null;
  changeType: "Modified" | "Added" | "Removed";
  original: string;
  revised: string;
  reason: string;
}

const buildReportText = (content: ExportInput["content"]): string => {
  const lines: string[] = [];
  lines.push("NYAYAI LEGAL CONTRACT ANALYSIS REPORT");
  lines.push("=".repeat(60));
  lines.push(`Generated: ${new Date().toLocaleString("en-IN")}`);
  if (content.contractType) lines.push(`Contract Type: ${content.contractType}`);
  lines.push("");
  lines.push(
    "This report is generated by an AI system with reference to the Indian Contract Act, 1872 and related Indian law. It is for informational purposes only and does not constitute legal advice.",
  );
  lines.push("");

  const summary = content.summary as Summary | undefined;
  if (summary) {
    lines.push("-".repeat(60));
    lines.push("EXECUTIVE SUMMARY");
    lines.push("-".repeat(60));
    lines.push(`Total clauses analyzed: ${summary.totalClauses}`);
    lines.push(`High-risk clauses: ${summary.riskyClausesCount}`);
    lines.push(`Moderate-risk clauses: ${summary.moderateRiskClausesCount}`);
    lines.push(`Overall risk level: ${summary.overallRiskLevel}`);
    if (summary.overview) {
      lines.push("");
      lines.push(summary.overview);
    }
    lines.push("");
  }

  const missingClauses = (content.missingClauses ?? []) as Missing[];
  if (missingClauses.length > 0) {
    lines.push("-".repeat(60));
    lines.push("POTENTIALLY MISSING CLAUSES");
    lines.push("-".repeat(60));
    missingClauses.forEach((clause, i) => {
      lines.push(`${i + 1}. [${clause.importance}] ${clause.clauseName}`);
      lines.push(`   Suggestion: ${clause.suggestion}`);
      lines.push("");
    });
  }

  const socialFlags = (content.socialFlags ?? []) as Social[];
  if (socialFlags.length > 0) {
    lines.push("-".repeat(60));
    lines.push("SOCIAL CONTEXT FLAGS");
    lines.push("-".repeat(60));
    socialFlags.forEach((flag, i) => {
      lines.push(`${i + 1}. "${flag.flaggedText}"`);
      lines.push(`   ${flag.explanation}`);
      lines.push("");
    });
  }

  const clauses = (content.clauses ?? []) as Clause[];
  if (clauses.length > 0) {
    lines.push("-".repeat(60));
    lines.push("CLAUSE-BY-CLAUSE BREAKDOWN");
    lines.push("-".repeat(60));
    clauses
      .slice()
      .sort((a, b) => a.clauseNumber - b.clauseNumber)
      .forEach((clause) => {
        lines.push(
          `Clause ${clause.clauseNumber} - ${clause.clauseType} [${clause.riskLevel}, score ${clause.riskScore.toFixed(2)}]`,
        );
        lines.push(`Text: "${clause.clauseText}"`);
        lines.push(`Legal basis: ${clause.legalBasis}`);
        lines.push(`Analysis: ${clause.explanation}`);
        lines.push(`Suggestion: ${clause.suggestion}`);
        if (clause.xaiExplanation.length > 0) {
          lines.push("Explainable AI — key risk factors:");
          clause.xaiExplanation.forEach((x: XaiExplanationEntry) => {
            lines.push(`  - "${x.word}" (importance ${(x.importance * 100).toFixed(0)}%): ${x.reason}`);
          });
        }
        lines.push("");
      });
  }

  const changeLog = (content.changeLog ?? []) as ChangeEntry[];
  const updatedContractText = content.updatedContractText;
  if (updatedContractText) {
    lines.push("-".repeat(60));
    lines.push("UPDATED CONTRACT (RISK-MITIGATED VERSION)");
    lines.push("-".repeat(60));
    lines.push(updatedContractText);
    lines.push("");
  }
  if (changeLog.length > 0) {
    lines.push("-".repeat(60));
    lines.push("CHANGE LOG");
    lines.push("-".repeat(60));
    changeLog.forEach((entry, i) => {
      lines.push(`${i + 1}. [${entry.changeType}]${entry.clauseNumber != null ? ` Clause ${entry.clauseNumber}` : ""}`);
      lines.push(`   Original: ${entry.original}`);
      lines.push(`   Revised: ${entry.revised}`);
      lines.push(`   Reason: ${entry.reason}`);
      lines.push("");
    });
  }

  return lines.join("\n");
};

const buildContractOnlyText = (content: ExportInput["content"]): string => {
  const lines: string[] = [];
  lines.push("NYAYAI — CORRECTED CONTRACT");
  lines.push("=".repeat(60));
  lines.push(`Generated: ${new Date().toLocaleString("en-IN")}`);
  lines.push(
    "This corrected contract was generated by an AI system with reference to the Indian Contract Act, 1872 and related Indian law. It is for informational purposes only and does not constitute legal advice. Have it reviewed by a qualified advocate before use.",
  );
  lines.push("");
  lines.push(content.updatedContractText ?? "");
  const changeLog = (content.changeLog ?? []) as ChangeEntry[];
  if (changeLog.length > 0) {
    lines.push("");
    lines.push("-".repeat(60));
    lines.push("SUMMARY OF CHANGES");
    lines.push("-".repeat(60));
    changeLog.forEach((entry, i) => {
      lines.push(`${i + 1}. [${entry.changeType}]${entry.clauseNumber != null ? ` Clause ${entry.clauseNumber}` : ""} — ${entry.reason}`);
    });
  }
  return lines.join("\n");
};

export const buildExportText = (input: ExportInput): string => {
  return input.content.kind === "contract"
    ? buildContractOnlyText(input.content)
    : buildReportText(input.content);
};

export const buildExportPdfBuffer = (input: ExportInput): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    const text = buildExportText(input);
    const doc = new PDFKit({ margin: 50, bufferPages: true });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const paragraphs = text.split("\n");
    doc.font("Helvetica");
    paragraphs.forEach((line) => {
      if (line.startsWith("=") || line.startsWith("-")) {
        doc.moveDown(0.3);
        return;
      }
      const isHeading = line === line.toUpperCase() && line.trim().length > 3 && !/["“]/.test(line);
      doc
        .fontSize(isHeading ? 12 : 10)
        .font(isHeading ? "Helvetica-Bold" : "Helvetica")
        .text(line || " ", { align: "left" });
    });

    doc.end();
  });
};
